version: "3.7"

services:
  boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USERNAME=test
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=authserver
      - DATABASE_PORT=3307
    restart: on-failure
    expose:
      - "8080"
    ports:
      - "8081:8080"

  mysql-service:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=authserver
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
    expose:
      - "3306"
    ports:
      - "3307:3306"