spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver?createDatabaseIfNotExist=true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    ord:
      hibernate:
        type: trace